version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5172:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
